type CountryRestrictionsType = {
    countryCode: string
    recruitmentProjectId: string
    countryName: string
    externalCountryId: number
    countryId: string
}

type contactPeopleType = {
    contactPersonId: string
    userId: string
    userName: string
    phoneNumber: string
    email: string
}

type RecruitmentProjectsType = {
    recruitmentProjectId: string
    type: string
    isActive: true
    companyId: number
    jobAdvertisementId: string
    companyName: string
    countryName: string
    countryId: string
    externalCountryId: number
    cityName: string
    projectStartDate: string
    projectEndDate: string
    workingStartDate: string
    workingEndDate: string
    modifiedOn: string
    numberOfAnyGenderVacancies: number
    numberOfManVacancies: number
    numberOfWomanVacancies: number
    numberOfVacancies: number
    destinationOfArrival: string
    category: string
    externalId: number
    externalSource: string
    typeOfContract: string
    typeOfContractId: string
    externalJobAdvertisementId: number
    companyGeoPosition: {
        srid: number
        lat: number
        long: number
    }
    closestBigCityGeoPosition: {
        srid: number
        lat: number
        long: number
    }
    minAge: number
    maxAge: number
    maximumNumberOfManVacanies: number
    maximumNumberOfWomenVacancies: number
    externalAllowGenderId: number
    allowBiometrics: true
    allowCouples: true
    allowGender: string
    countryRestrictions: CountryRestrictionsType[]
    nearestBigCitiesNameWithDistance: string
    nearestBigCityName: string
    comment: string
    payment: string
    vacancies: {
        currentNumberOfAnyGenderVacancies: number
        currentNumberOfManVacancies: number
        currentNumberOfWomanVacancies: number
        queueOfAnyGender: number
        queueOfMan: number
        queueOfWoman: number
        currentNumberOfManAndAnyVacancies: number
        currentNumberOfWomanAndAnyVacancies: number
        currentSumOfAllVacancies: number
    }
    isWithinDistance: true
    isInCountry: true
    orderId: string
}

export type NewProjectType = {
    id: string
    language: string
    jobPositionId: number
    correlationId: string
    status: string
    companyId: number
    companyName: string
    isFavorite: true
    typeOfContract: string
    typeOfContractId: string
    minAge: number
    maxAge: number
    allowGender: string
    externalAllowGenderId: number
    allowBiometrics: true
    allowCouples: true
    currencyCode: string
    currencyDisplayName: string
    grossHourlyRate: number
    netHourlyRate: number
    grossMonthlyRate: number
    netMonthlyRate: number
    weeklyMinimumWorkingTime: number
    weeklyMaximumWorkingTime: number
    jobPositionName: string
    modifiedByUsername: string
    personResponsibleForAdvertisement: string
    deductionForFlat: number
    deductionForForklifts: number
    transportationFee: number
    costOfClothes: number
    deductionForOccupationalMedicine: number
    typeOfWorkerAccommodation: string
    advertisementHtml: string
    mapTooltipHtml: string
    isManuallyEdited: true
    modifiedOn: string
    closestRecruitmentProjectEndDate: string
    closestRecruitmentProjectStartDate: string
    nearestBigCitiesNames: string
    alternativeBigCitiesNames: string
    cityNames: string
    numberOfMediaAttachments: number
    isVacancyAvailable: true
    tags: string
    tagArray: [string]
    recruitmentProjects: RecruitmentProjectsType[]
    countryRestrictions: CountryRestrictionsType[]
    contactPeople: contactPeopleType[]
}

export type CurrentProjectType = {
    advertisementHtml: string
    allowBiometrics: boolean
    allowCouples: boolean
    allowGender: string
    alternativeBigCitiesNames: string
    benefits: string
    boards: string
    cityNames: string
    closestRecruitmentProjectEndDate: string
    closestRecruitmentProjectStartDate: string
    companyId: number
    companyName: string
    contactPeople: contactPeopleType[]
    contractActivity: string
    correlationId: string
    costOfClothes: number
    countryRestrictions: CountryRestrictionsType[]
    currencyCode: string
    currencyDisplayName: string
    deductionForFlat: number
    deductionForForklifts: number
    deductionForOccupationalMedicine: number
    description: string
    externalAllowGenderId: 1
    grossHourlyRate: number
    grossMonthlyRate: number
    id: string
    isFavorite: boolean
    isManuallyEdited: boolean
    isVacancyAvailable: boolean
    jobPositionId: number
    jobPositionName: string
    language: string
    mapTooltipHtml: string
    marketingDescription: string
    maxAge: number
    minAge: number
    modifiedByUsername: string
    modifiedOn: string
    nearestBigCitiesNames: string
    netHourlyRate: number
    netMonthlyRate: number
    numberOfMediaAttachments: number
    penaltiesAndFees: string
    personResponsibleForAdvertisement: string
    recruitmentProjects: RecruitmentProjectsType[]
    requirements: string
    tagArray: [string]
    tags: string
    transportationFee: number
    typeOfContract: string
    typeOfContractId: string
    typeOfWorkerAccommodation: string
    weeklyMaximumWorkingTime: number
    weeklyMinimumWorkingTime: number
    workType: any
}
